server:
  port: ${PORT:8093}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3361}/${DB_NAME:bank_ms_db}
    username: root
    password: ${DB_PASS:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: bank
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  config:
    import: ${CONFIG_HOST:optional:configserver:http://localhost:8070/}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

customer:
  url: ${CUSTOMER_HOST:http://localhost:8000/api/customers/}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

endpoints:
  shoutdown:
    enabled: true

  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_HOST:http://localhost:8071/eureka/}

info:
  app:
    name: "Bank"
    description: "Bank system to process customers request"
    version: "1.0.0"

logging:
  level:
    com:
      juliluis:
        bankms: DEBUG