server:
  port: ${PORT:8093}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3361}/${DB_NAME:bank_ms_db}
    username: root
    password: ${DB_PASS:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: bank
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  config:
    import: "optional:configserver:http://localhost:8070/"

customer:
  url: ${CUSTOMER_HOST:http://localhost:8000/api/customers/}

management:
  endpoints:
    web:
      exposure:
        include: "*"
