server:
  port: ${PORT:8093}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3361}/${DB_NAME:bank_ms_db}
    username: root
    password: ${DB_PASS:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: bank-ms
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  config:
    import:
      - "application_qa.yaml"
      - "application_prod_yaml"
  profiles:
    active:
      - "qa"
customer:
  url: ${CUSTOMER_HOST:http://localhost:8000/api/customers/}

build:
  version: 1.0

contact:
  email: "dev@server.com"
  phones:
    - 809-549-3625
    - 809-549-5549



