version: "3.8"
services:
  banktranx:
    image: jpelegrino/bank:1.0
    container_name: bankservice
    ports:
      - "8093:8093"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - wiremoney
    depends_on:
      - bankdb
      - customers
    environment:
      DB_HOST: bankdb
      DB_PASS: admin
      DB_NAME: bank-db
      CUSTOMER_HOST: http://customers:8000/api/customers/




  customers:
    image: jpelegrino/customers:1.0
    container_name: customerservice
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - wiremoney
    depends_on:
      - customerdb
    environment:
      DB_HOST: customerdb
      DB_PASS: admin
      DB_NAME: customer-db

  wiretransfer:
    image: jpelegrino/wiretransfer:1.0
    container_name: wiretransfer
    ports:
      - "8001:8001"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - wiremoney
    depends_on:
      - banktranx
    environment:
      BANK_HOST: http://banktranx:8093/transactions


  customerdb:
    image: mysql:8.0
    container_name: customerdb-serv
    ports:
      - "3362:3306"
    expose:
      - "3362"
    volumes:
      - customerdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: customer-db
    networks:
      - wiremoney

  bankdb:
    image: mysql:8.0
    container_name: bank-serv
    ports:
      - "3363:3306"
    expose:
      - "3363"
    volumes:
      - bankdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: bank-db
    networks:
      - wiremoney


networks:
  wiremoney:
    driver: "bridge"

volumes:
  customerdata:
  bankdata:
